title: Angelo Morris # your name (or website title) here
logo: "/images/logo-cropped.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Aspiring Engineer
  <br><br>
  <a href="https://github.com/Angelo-Morris">My GitHub</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
